version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "BaldursGate4301"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: DndSolution.WebApi/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DndSolution;User Id=sa;Password=BaldursGate4301;TrustServerCertificate=True;"

  worker:
    build:
      context: .
      dockerfile: DndSolution.Worker/Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DndSolution;User Id=sa;Password=BaldursGate4301;TrustServerCertificate=True;"

  frontend:
    build:
      context: ./dnd-solution-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - webapi

volumes:
  sqlserverdata: